### ISSUE TITLE
Falsche Werte WG796E.1

### ISSUE THREAD

**Issue by Matzebhv** [iobroker-community-adapters/ioBroker.landroid#11]
Moin,
habe heute meinen Landroid erhalten. Er steht derzeit in seiner Ladestation.

Der Adapter ist verbunden, allerdings zeigt der Datenpunkt batteryState 100% ( tatsächlich 91% ) und der Datenpunkt distance hat einen negativen Wert, der bei jedem Refresh größer wird. Derzeit -384m
Firmware 2.47
Gruß
Matze

**Comment by Matzebhv** [comment]
Jetzt ist der Akku tatsächlich voll, batteryChargerState ist auf idle, der Wert distance verändert sich nun nicht mehr.

**Comment by hermx** [comment]
Hab's mir angeschaut,
bekomme die gleichen falschen Werte. Sie kommen so aus dem Gerät und können mittels http://xxx.xxx.x.xxx/debugPage.html formatiert anzeigbar.
Anderer Zugang zum Gerät ist mir nicht bekannt. Die Einheiten sind nicht 'echt'.
Kennt jemand Fundierteres?

**Comment by ldittmar81** [comment]
Leider habe ich kein Landroid mehr und kann es nicht mehr überprüfen. Wenn jemand eine Idee hat, dann her damit!

**Comment by runsnbunsn** [comment]
Kann das mit der Distance bestätigen, sie stimmt jedoch wieder sobald der Mäher startet. Könnte damit zu tun haben dass er rückwärts aus der Ladestation fährt. Und die Einheit ist in Millimeter soweit ich mich erinnere. Hab heuer schon alles abgebaut, sonst könnte ich nachsehen...

**Comment by mcm1957** [comment]
Currently no further development is planned for this adapter. Please use ioBroker.worx.
