### ISSUE TITLE
message-handler-implemented-but-messagebox-not-enabled

### ISSUE THREAD

**Issue by ldittmar81** [iobroker-community-adapters/ioBroker.landroid#17]
Hallo ldittmar,

ich hoffe es ist ok, dass ich mich via EMail melde,
da ich noch keinen github-account habe.

Ich habe den Adapter neu ausprobiert, leider bekomme ich keine Werte
in die Objekte, PIN sollte richtig hinterlegt sein.

Zuerst war noch ein Fehler wegen message box, siehe hier:
https://forum.iobroker.net/topic/14391/gel%C3%B6st-fehler-beim-start-der-javascript-instanzen-message-handler-implemented-but-messagebox-not-enabled/13

Anscheinend ist bei meinem Landroid L kein port 80 offen nmap und wget
sagen dazu *issnich*

Grüße

Markus

**Comment by mcm1957** [comment]
Currently no further development is planned for this adapter. Please use ioBroker.worx.
