### ISSUE TITLE
Think about to fix the issues found by adapter checker

### ISSUE THREAD

**Issue by ioBrokerChecker** [iobroker-community-adapters/ioBroker.landroid#19]
I am an automatic service that looks for possible errors in ioBroker and creates an issue for it. The link below leads directly to the test:

https://adapter-check.iobroker.in/?q=https://raw.githubusercontent.com/iobroker-community-adapters/ioBroker.landroid

- [ ] [E149] instanceObject common.type has an invalid value: switch
- [ ] [E150] No common.connectionType found in io-package.json
- [ ] [E152] No common.dataSource found in io-package.json
- [ ] [E140] width and height of logo are not equal
- [ ] [E504] found setInterval in "main.js, but no clearInterval detected
- [ ] [E301] Tests on Travis-ci.org are broken. Please fix.
- [ ] [E605] No actual year found in copyright. Please add "Copyright (c) 2018-2021 ldittmar <iobroker@lmdsoft.de>" at the end of README.md
- [ ] [E701] No actual year found in LICENSE. Please add "Copyright (c) 2021 ldittmar <iobroker@lmdsoft.de>" at the start of LICENSE

Thanks,
your automatic adapter checker.

**Comment by ioBrokerChecker** [comment]
Do you need help fixing the bugs?

**Comment by mcm1957** [comment]
outdated
