### ISSUE TITLE
2019 Mower integration

### ISSUE THREAD

**Issue by fu-zhou** [iobroker-community-adapters/ioBroker.landroid#21]
Hallo, ich habe einen Landroid M500 Mäher (2019). Im Adapter wird nur "Connection: True" angezeigt, alle anderen Werte bleiben leer. Kann es sein, dass der Adapter (noch) nicht kompatibel ist, mit den neuen Geräten (FW 2.74)

**Comment by ldittmar81** [comment]
Hi... Kann gut möglich sein, aber ich habe das Problem, dass ich kein Landroid mehr besitze... Meine Ex hat ihn nach der Scheidung behalten... Naja... Ich schaue mal im Netz ob ich was dazu finde und wenn ja, passe ich den Adapter an. Nur testen könnte ich es dann nicht.

**Comment by fu-zhou** [comment]
Ich stehe fast jederzeit zum Testen bereit!

**Comment by necotec** [comment]
Hier auch ein williger tester :)

Habe den Adapter zwar noch nicht installiert, da die WLAN Strecke erst ausgebaut werden muss, allerdings habe ich großes Interesse.

Ich habe einen Worx Landroid L1500i. Funktioniert der Adapter eventuell bereits mit dem Gerät?

**Comment by moyo77** [comment]
Ich habe auch das Problem, dass der Adapter läuft aber außer das unter Status "true" angezeigt wird, keine weiteren Werte angezeigt werden. Teste natürlich auch gerne.

**Comment by Michaelnorge** [comment]
Hier ist noch jemand, der sich gerne anschließt.
Hab einen M1000 (2019) und wie bei den Vorgängern steht hier bei mir nur der Status auf "true", sonst wird nichts angezeigt.

Die Log schreibt:
 : message handler implemented, but messagebox not enabled. Define common.messagebox in io-package.json for adapter or delete message handler.
 Please configure the Landroid Adapter

**Comment by schneie** [comment]
Hallo, gibt es hier neue Erkenntnisse!?
Die neue Mähsaison steht vor der Tür und ich stehe noch vor dem gleichen hier beschriebenen Problem...
VG Markus

**Comment by fu-zhou** [comment]
Meine Erkenntnis ist, dass ich den anderen Adapter installiert habe (Worx Landorid Cloud V1.0.0). Damit funktioniert erst mal alles, Rasenmäher Offline nehmen habe ich jetzt noch nicht probiert. Interessanterweise ist der "alte" Adapter nicht mehr verfügbar. Ich habe ihn deinstalliert und dann wird er nicht mehr angeboten, wenn man nach Landroid sucht. Macht aber nix, der Cloud Adapter funktioniert gut...

**Comment by schneie** [comment]
Hab ich jetzt auch so gemacht. Funktioniert. Danke!

**Comment by sam-75** [comment]
Hi, 
habe einen Landroid S WR106SI - FW: 3.52
Leider selber effekt alles grün aber keine Werte. 
Weiter ist es ihm wohl auch egal was bei der Pin eingegeben wird ist immer grün.
Denke die alten Modelle haben keine PIN.
Gerne auch bereit mit dem Adapter zu testen.

**Comment by mgernhard** [comment]
Guten Tag,

soweit wie die anderen komme ich leider noch nicht.

Die Instanz verbindet sich nichtmal mit dem Landroid M500.
Scheint so als sei ich nicht der erste mit dem Problem
Werden die daten über (http://Admin:1909@192.168.231.81/jsondata.cg) ausgelesen? Siehe:
https://www.roboter-forum.com/index.php?thread/34863-api-heimautomatisierung/

Habe das letzte Update auf den Landroid M500 aufgespielt. (3.17)
Der Mäher befindet sich ein einem anderen VLAN, das sollte aber keine Probleme machen denke ich. Wenn ich falsch liege bitte sagen. Firewallregeln zwischen den VLANs sind deaktiviert.

Stehe auch gerne zum Testen zur Verfügung @ldittmar81 auch wenn es die Situation aktuell schwer gestalltet.

**Comment by mcm1957** [comment]
Currently no further development is planned for this adapter. Please use ioBroker.worx.
