### ISSUE TITLE
(17345) Connection blocked from Worx, please try again in 24h

### ISSUE THREAD

**Issue by notkom** [iobroker-community-adapters/ioBroker.landroid#29]
No connection to the Worx server. The connection is blocked by Worx. This means that no status data can be queried.

Error message in the log: 
(17345) Connection blocked from Worx, please try again in 24h

---

**System data:**

Model: ARMv7 Processor rev 3 (v7l)
RAM: 3.81 GB
Node.js: v10.19.0
NPM: 6.13.4
Platform: linux
Distribution: Raspbian GNU/Linux
Architecture: arm
JS-Controller (1): 2.2.9
Admin: 4.0.5
WORX Landroid: 1.0.3

> *created by ioBroker.info*

**Comment by notkom** [comment]
**Feedback from Worx Support**

> _If you use an unofficial app, software or suite, you should uninstall it and disconnect it from the robot.  We only support the official Worx Landroid app, which you can download from the App Store / Play Store.  Most third-party apps can negatively impact server settings, so we won't support them for now.  We would like to point out that some of these apps could be classified as malicious by our security systems, which will result in the account being temporarily  blocked._ >

**Comment by mcm1957** [comment]
Currently no further development is planned for this adapter. Please use ioBroker.worx.
